### PR TITLE
[Feature] - Use Mdbook to display and typeset articles.

### PR DESCRIPTION
**Pull request by francis-du**
- Link to  #1 

- Preview: https://francis-du.github.io/Technical_Communication/

- Need help:  Add an access token for this repo

1. Go to your Account Settings -> profile -> Developer settings -> Generate Personal access token and copy it.

image

image

2. Go to this repo Settings -> secrets -> New Secrets -> Secrets  Name is `DEPLOY_KEY` ,value is you access token.

image

### CODE REVIEW

**Comment by francis-du** [comment]
> [CLA assistant check](https://cla-assistant.io/ireneontheway/Technical_Communication?pullRequest=2)
> All committers have signed the CLA.

Hi @ireneontheway 

This CLA  is default. if you need this , you should add your CLA file.

**Comment by ireneontheway** [comment]
I've signed the CLA. I'll review your commit later. Thanks a lot.

**Comment by ireneontheway** [comment]
Done @francis-du

**Comment by francis-du** [comment]
@ireneontheway I resolve the conflicting files.

**Comment by francis-du** [comment]
- Preview: https://francis-du.github.io/Technical_Communication/

- Need help: 

  Hi Irene, can you rename this repo to `ireneontheway.github.io`,

then you can use it to visit your website.

**Comment by francis-du** [comment]
Hi Irene: 

I found that changing the name of the repo will cause the links already 

posted on Twitter to be inaccessible.So I suggest to re-create a new repo

named `ireneontheway.github.io` .And you we still need  an access token.

This PR will be closed.

**Comment by ireneontheway** [comment]
> Hi Irene:
> 
> I found that changing the name of the repo will cause the links already
> 
> posted on Twitter to be inaccessible.So I suggest to re-create a new repo
> 
> named `ireneontheway.github.io` .And you we still need an access token.
> 
> This PR will be closed.

Is it ok to rename it as " technicalcommunication.github.io"? @francis-du

**Comment by francis-du** [comment]
> > Hi Irene:
> > I found that changing the name of the repo will cause the links already
> > posted on Twitter to be inaccessible.So I suggest to re-create a new repo
> > named `ireneontheway.github.io` .And you we still need an access token.
> > This PR will be closed.
> 
> Is it ok to rename it as " technicalcommunication.github.io"? @francis-du

Please create new repo, name is `ireneontheway.github.io`, i will re-commit.

**Pull request closed without merging**
